### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by CrypticCus** [luzeadev/winactivate#1]
May i ask for 2 things
1) Can u add support for KMS to activate office? or else i will put abbodis aio script in silent mode inside but i don't want to since its your project
2) Can u place slc.dll and gatherosstate.exe inside the script by compressing it as text? so only 1 file.

**Comment by luzeadev** [comment]
Hi, unfortunately, I don't plan to add support for Office. First, because Office doesn't support HWID/KMS38 activation and second, because this script was only meant for activating Windows, not Office. I advise you to use KMS_VL_ALL for that purpose.

By the way, compressed archives with all the files can be found here: https://github.com/luzeadev/winactivate/releases

**Comment by CrypticCus** [comment]
i mean compressed to TEXT not archive but thats ok u won't do it i understand.

**Comment by luzeadev** [comment]
I completely understood what you meant, and no, I won’t "compress it to TEXT". Windows is capable of unzipping compressed (.zip) archives out of the box and you’re advised to make use of this feature. Can I close the issue?
